const express = require('express');
const authRoutes = require('./auth.routes');
const companiesRoutes = require('./companies.routes');
const branchesRoutes = require('./branches.routes');
const membershipsRoutes = require('./memberships.routes');
const modulesRoutes = require('./modules.routes');
const adminRoutes = require('./admin.routes');
const adminAiAssistantRoutes = require('./admin-ai-assistant.routes');
const legalRoutes = require('./legal.routes');
const supportRoutes = require('./support.routes');
const deadlinesRoutes = require('./deadlines.routes');
const myDeadlinesRoutes = require('./my-deadlines.routes');
const businessStatusRoutes = require('./business-status.routes');
const staffDocumentsRoutes = require('./staff-documents.routes');
const dailyTasksRoutes = require('./daily-tasks.routes');
const dashboardRoutes = require('./dashboard.routes');
const journalsRoutes = require('./journals.routes');
const generatedJournalsRoutes = require('./generated-journals.routes');
const dossierRoutes = require('./dossier.routes');
const pushRoutes = require('./push.routes');
const clientErrorsRoutes = require('./client-errors.routes');
const subscriptionRoutes = require('./subscription.routes');
const landingRoutes = require('./landing.routes');
const roadmapRoutes = require('./roadmap.routes');
const businessPassportRoutes = require('./businessPassport.routes');
const franchiseRoutes = require('./franchise.routes');
const addonsRoutes = require('./addons.routes');
const aiAdvisorSubscriptionRoutes = require('./ai-advisor-subscription.routes');
const anonymousAuditRoutes = require('./anonymous-audit.routes');
const leadsPublicRoutes = require('./leads-public.routes');
const yandexCardAuditRoutes = require('./yandex-card-audit.routes');

const platformRouter = express.Router();
platformRouter.use('/companies', companiesRoutes);
platformRouter.use('/branches', branchesRoutes);
platformRouter.use('/memberships', membershipsRoutes);
platformRouter.use('/modules', modulesRoutes);
platformRouter.use('/admin', adminRoutes);
platformRouter.use('/admin-ai-assistant', adminAiAssistantRoutes);
platformRouter.use('/support', supportRoutes);
platformRouter.use('/deadlines', deadlinesRoutes);
platformRouter.use('/my-deadlines', myDeadlinesRoutes);
platformRouter.use('/business-status', businessStatusRoutes);
platformRouter.use('/staff-documents', staffDocumentsRoutes);
platformRouter.use('/daily-tasks', dailyTasksRoutes);
platformRouter.use('/dashboard', dashboardRoutes);
platformRouter.use('/journals', journalsRoutes);
platformRouter.use('/generated-journals', generatedJournalsRoutes);
platformRouter.use('/dossier', dossierRoutes);
platformRouter.use('/push', pushRoutes);
platformRouter.use('/client-errors', clientErrorsRoutes);
platformRouter.use('/subscription', subscriptionRoutes);
platformRouter.use('/landing', landingRoutes);
platformRouter.use('/roadmap', roadmapRoutes);
platformRouter.use('/business-passport', businessPassportRoutes);
platformRouter.use('/franchise', franchiseRoutes);
platformRouter.use('/addons', addonsRoutes);
platformRouter.use('/ai-advisor-subscription', aiAdvisorSubscriptionRoutes);
platformRouter.use('/anonymous-audit', anonymousAuditRoutes);
platformRouter.use('/leads-public', leadsPublicRoutes);
platformRouter.use('/yandex-card-audit', yandexCardAuditRoutes);

module.exports = { authRoutes, platformRouter, legalRoutes };
