const express = require('express');
const authRoutes = require('./auth.routes');
const companiesRoutes = require('./companies.routes');
const branchesRoutes = require('./branches.routes');
const membershipsRoutes = require('./memberships.routes');
const modulesRoutes = require('./modules.routes');
const adminRoutes = require('./admin.routes');
const legalRoutes = require('./legal.routes');
const supportRoutes = require('./support.routes');
const deadlinesRoutes = require('./deadlines.routes');
const myDeadlinesRoutes = require('./my-deadlines.routes');
const staffDocumentsRoutes = require('./staff-documents.routes');
const dailyTasksRoutes = require('./daily-tasks.routes');
const dashboardRoutes = require('./dashboard.routes');
const journalsRoutes = require('./journals.routes');
const generatedJournalsRoutes = require('./generated-journals.routes');
const dossierRoutes = require('./dossier.routes');
const pushRoutes = require('./push.routes');

const platformRouter = express.Router();
platformRouter.use('/companies', companiesRoutes);
platformRouter.use('/branches', branchesRoutes);
platformRouter.use('/memberships', membershipsRoutes);
platformRouter.use('/modules', modulesRoutes);
platformRouter.use('/admin', adminRoutes);
platformRouter.use('/support', supportRoutes);
platformRouter.use('/deadlines', deadlinesRoutes);
platformRouter.use('/my-deadlines', myDeadlinesRoutes);
platformRouter.use('/staff-documents', staffDocumentsRoutes);
platformRouter.use('/daily-tasks', dailyTasksRoutes);
platformRouter.use('/dashboard', dashboardRoutes);
platformRouter.use('/journals', journalsRoutes);
platformRouter.use('/generated-journals', generatedJournalsRoutes);
platformRouter.use('/dossier', dossierRoutes);
platformRouter.use('/push', pushRoutes);

module.exports = { authRoutes, platformRouter, legalRoutes };
